image:
  file: .gitpod.Dockerfile

tasks:
  - name: Init project and run server
    init: |
      echo "1"

      PROJECT_NAME="flaskr"

      if test ! -e "${PROJECT_NAME}"; then {
        tmp_dir=/tmp/.fgc
        git clone --filter=tree:0 https://github.com/pallets/flask "${tmp_dir}"
        mv "${tmp_dir}/examples/tutorial"/{.*,*} . 2>/dev/null
        rm -rf "${tmp_dir}"
      } fi

      pip install -e .
      if test -e "${PROJECT_NAME}"; then {
        flask --app "${PROJECT_NAME}" init-db
      } fi

    command: |
      PROJECT_NAME="flaskr"

      flask --app "${PROJECT_NAME}" run --debug

ports:
  - port: 5000
    onOpen: open-preview
    description: Flask App preview

vscode:
  extensions:
    - ms-python.python

